//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Test
{

    private TestQuestion[] questionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Question")]
    public TestQuestion[] Question
    {
        get
        {
            return this.questionField;
        }
        set
        {
            this.questionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TestQuestion
{

    private string questionTextField;

    private int numberOfParagraphsField;

    private bool numberOfParagraphsFieldSpecified;

    private int totalNumberOfWordsField;

    private bool totalNumberOfWordsFieldSpecified;

    private TestQuestionAnswer answerField;

    private TestQuestionOption1 option1Field;

    private TestQuestionOption2 option2Field;

    private TestQuestionOption3 option3Field;

    private TestQuestionOption4 option4Field;

    private string typeField;

    private int numberField;

    /// <remarks/>
    public string QuestionText
    {
        get
        {
            return this.questionTextField;
        }
        set
        {
            this.questionTextField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int NumberOfParagraphs
    {
        get
        {
            return this.numberOfParagraphsField;
        }
        set
        {
            this.numberOfParagraphsField = value;
        }
    }

    ///// <remarks/>
    //[System.Xml.Serialization.XmlIgnoreAttribute()]
    //public bool NumberOfParagraphsSpecified
    //{
    //    get
    //    {
    //        return this.numberOfParagraphsFieldSpecified;
    //    }
    //    set
    //    {
    //        this.numberOfParagraphsFieldSpecified = value;
    //    }
    //}

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int TotalNumberOfWords
    {
        get
        {
            return this.totalNumberOfWordsField;
        }
        set
        {
            this.totalNumberOfWordsField = value;
        }
    }

    ///// <remarks/>
    //[System.Xml.Serialization.XmlIgnoreAttribute()]
    //public bool TotalNumberOfWordsSpecified
    //{
    //    get
    //    {
    //        return this.totalNumberOfWordsFieldSpecified;
    //    }
    //    set
    //    {
    //        this.totalNumberOfWordsFieldSpecified = value;
    //    }
    //}

    /// <remarks/>
    public TestQuestionAnswer Answer
    {
        get
        {
            return this.answerField;
        }
        set
        {
            this.answerField = value;
        }
    }

    /// <remarks/>
    public TestQuestionOption1 Option1
    {
        get
        {
            return this.option1Field;
        }
        set
        {
            this.option1Field = value;
        }
    }

    /// <remarks/>
    public TestQuestionOption2 Option2
    {
        get
        {
            return this.option2Field;
        }
        set
        {
            this.option2Field = value;
        }
    }

    /// <remarks/>
    public TestQuestionOption3 Option3
    {
        get
        {
            return this.option3Field;
        }
        set
        {
            this.option3Field = value;
        }
    }

    /// <remarks/>
    public TestQuestionOption4 Option4
    {
        get
        {
            return this.option4Field;
        }
        set
        {
            this.option4Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Number
    {
        get
        {
            return this.numberField;
        }
        set
        {
            this.numberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TestQuestionAnswer
{

    private string[] keywordField;

    private string textField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Keyword")]
    public string[] Keyword
    {
        get
        {
            return this.keywordField;
        }
        set
        {
            this.keywordField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TestQuestionOption1
{

    private string answerField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Answer
    {
        get
        {
            return this.answerField;
        }
        set
        {
            this.answerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TestQuestionOption2
{

    private string answerField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Answer
    {
        get
        {
            return this.answerField;
        }
        set
        {
            this.answerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TestQuestionOption3
{

    private string answerField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Answer
    {
        get
        {
            return this.answerField;
        }
        set
        {
            this.answerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class TestQuestionOption4
{

    private string answerField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Answer
    {
        get
        {
            return this.answerField;
        }
        set
        {
            this.answerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}
